// #pragma checksum "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/Pages/StateManagement/StateManagementDemo.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2a4e2a0d76c69c2a6b8e98341f17ed5be6c8891c"
// // <auto-generated/>
// #pragma warning disable 1591
// namespace __GeneratedComponent
// {
//     #line hidden
// #nullable restore
// #line 2 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using System.Net.Http;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 3 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using System.Net.Http.Json;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 5 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using Microsoft.AspNetCore.Components.Routing;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 6 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using Microsoft.AspNetCore.Components.Web;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 7 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using Microsoft.AspNetCore.Components.Web.Virtualization;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 8 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using Microsoft.JSInterop;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 9 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using Microsoft.AspNetCore.Components.Forms;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 10 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using System.Text.Json;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 14 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using blazor_dotnet06.Shared;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 15 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using blazor_dotnet06.ViewModel;

// #line default
// #line hidden
// #nullable disable
// #nullable restore
// #line 16 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/_Imports.razor"
// using blazor_dotnet06.Services;

// #line default
// #line hidden
// #nullable disable
//     [Microsoft.AspNetCore.Components.RouteAttribute("/state-management")]
//     public partial class AspNetCore_2a4e2a0d76c69c2a6b8e98341f17ed5be6c8891c : Microsoft.AspNetCore.Components.ComponentBase
//     {
//         #pragma warning disable 1998
//         protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
//         {
//             __builder.OpenElement(0, "div");
//             __builder.AddAttribute(1, "class", "container");
//             __builder.AddMarkupContent(2, "<h3>State management</h3>\n    ");
//             __builder.AddMarkupContent(3, "<h3 class=\"alert alert-warning\">\n        Tăng giảm số lượng\n    </h3>\n    ");
//             __builder.OpenElement(4, "button");
//             __builder.AddAttribute(5, "class", "btn btn-dark me-2");
//             __builder.AddAttribute(6, "@onclick", 
// #nullable restore
// #line 9 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/Pages/StateManagement/StateManagementDemo.razor"
//                                                   (e) => handleChangeNumber(1)

// #line default
// #line hidden
// #nullable disable
//             );
//             __builder.AddContent(7, "+");
//             __builder.CloseElement();
//             __builder.AddMarkupContent(8, "\n    ");
//             __builder.OpenElement(9, "h3");
//             __builder.AddAttribute(10, "class", "d-inline-block");
// #nullable restore
// #line 10 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/Pages/StateManagement/StateManagementDemo.razor"
// __builder.AddContent(11, _numService.number);

// #line default
// #line hidden
// #nullable disable
//             __builder.CloseElement();
//             __builder.AddMarkupContent(12, "\n    ");
//             __builder.OpenElement(13, "button");
//             __builder.AddAttribute(14, "class", "btn btn-dark ms-2");
//             __builder.AddAttribute(15, "@onclick", 
// #nullable restore
// #line 11 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/Pages/StateManagement/StateManagementDemo.razor"
//                                                   (e) => handleChangeNumber(-1)

// #line default
// #line hidden
// #nullable disable
//             );
//             __builder.AddContent(16, "-");
//             __builder.CloseElement();
//             __builder.CloseElement();
//         }
//         #pragma warning restore 1998
// #nullable restore
// #line 16 "/Volumes/Cybersoft/dotnet06/web_blazor/blazor_dotnet06/Pages/StateManagement/StateManagementDemo.razor"
       

//     public async Task handleChangeNumber(int quantity) {
//        await  _numService.changeNumber(quantity);
//     } 
//     protected override async Task OnInitializedAsync() {
//         //Cài đặt event onchange trên lifecycle init
//         _numService.OnChange += StateHasChanged;
//     }


// #line default
// #line hidden
// #nullable disable
//         [global::Microsoft.AspNetCore.Components.InjectAttribute] private NumberService _numService { get; set; }
//     }
// }
// #pragma warning restore 1591
